<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="China Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="LWFWIND-7BB2A92"><DocLocation><![CDATA[C:\Documents and Settings\lwfwind\Desktop\SimpleQTP V3.4\MainScript]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[MainScript]]></DName>
<Res><![CDATA[Res9]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:07]]></Time>
<TimeTick>1322373487</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Login.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:07]]></Time>
<TimeTick>1322373487</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Agent Name:.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:07]]></Time>
<TimeTick>1322373487</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Password:.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:08]]></Time>
<TimeTick>1322373488</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="20" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Password:.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:08]]></Time>
<TimeTick>1322373488</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="25" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[IsContextLoaded]]></Obj>
<Details ><![CDATA[
Object #1Login_Dialog was not found.Please check the object properies
Object #2AgentName was not found.Please check the object properies
Object #3Password was not found.Please check the object properies
Object #4OK was not found.Please check the object properies]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:08]]></Time>
<TimeTick>1322373488</TimeTick>
<NodeArgs eType="User" icon="8" nRep="26" status="Warning" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[IsContextLoaded]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Login.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="27" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Agent Name:.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="28" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Password:.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="29" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Password:.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="30" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[IsContextLoaded]]></Obj>
<Details ><![CDATA[
Object #1Login_Dialog was found.
Object #2AgentName was found.
Object #3Password was found.
Object #4OK was found.]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="User" icon="8" nRep="31" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[IsContextLoaded]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[GUI Layer initialization]]></Obj>
<Details ><![CDATA[All Login GUI context objects have been loaded successfully]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="User" icon="8" nRep="32" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[GUI Layer initialization]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="34" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[SetAgentName]]></Obj>
<Details ><![CDATA[Set successfully]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="User" icon="8" nRep="35" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SetAgentName]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Password:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="37" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Password:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[SetPassword]]></Obj>
<Details ><![CDATA[Set successfully]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="User" icon="8" nRep="38" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SetPassword]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="40" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[Submit]]></Obj>
<Details ><![CDATA[Login successfully]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="User" icon="8" nRep="41" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Submit]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" status="Warning" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Flight Reservation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="44" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[MaskEdBox.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="49" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[MaskEdBox.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Fly From:.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="54" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Fly From:.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Fly To:.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="59" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Fly To:.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[FLIGHT.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="64" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[FLIGHT.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Name:.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="69" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Name:.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Insert Order.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="74" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Insert Order.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Threed Panel Control.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="79" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Threed Panel Control.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA[IsContextLoaded]]></Obj>
<Details ><![CDATA[
Object #1Flight Reservation was not found.Please check the object properies
Object #2Date was not found.Please check the object properies
Object #3FlyFrom was not found.Please check the object properies
Object #4FlyTo was not found.Please check the object properies
Object #5FLIGHT_button was not found.Please check the object properies
Object #6Name was not found.Please check the object properies
Object #7Insert Order was not found.Please check the object properies
Object #8ProgressBar was not found.Please check the object properies]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:10]]></Time>
<TimeTick>1322373490</TimeTick>
<NodeArgs eType="User" icon="8" nRep="80" status="Warning" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[IsContextLoaded]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Flight Reservation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:14]]></Time>
<TimeTick>1322373494</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="82" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[MaskEdBox.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:14]]></Time>
<TimeTick>1322373494</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="87" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[MaskEdBox.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Fly From:.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:14]]></Time>
<TimeTick>1322373494</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="92" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Fly From:.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Fly To:.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:14]]></Time>
<TimeTick>1322373494</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="93" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Fly To:.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[FLIGHT.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:14]]></Time>
<TimeTick>1322373494</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="94" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[FLIGHT.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Name:.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:14]]></Time>
<TimeTick>1322373494</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="95" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Name:.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Insert Order.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:14]]></Time>
<TimeTick>1322373494</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="96" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Insert Order.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Threed Panel Control.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:14]]></Time>
<TimeTick>1322373494</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="97" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Threed Panel Control.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[IsContextLoaded]]></Obj>
<Details ><![CDATA[
Object #1Flight Reservation was not found.Please check the object properies
Object #2Date was not found.Please check the object properies
Object #3FlyFrom was not found.Please check the object properies
Object #4FlyTo was not found.Please check the object properies
Object #5FLIGHT_button was not found.Please check the object properies
Object #6Name was not found.Please check the object properies
Object #7Insert Order was not found.Please check the object properies
Object #8ProgressBar was not found.Please check the object properies]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:14]]></Time>
<TimeTick>1322373494</TimeTick>
<NodeArgs eType="User" icon="8" nRep="98" status="Warning" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[IsContextLoaded]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Flight Reservation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:16]]></Time>
<TimeTick>1322373496</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="99" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[MaskEdBox.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:16]]></Time>
<TimeTick>1322373496</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="100" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[MaskEdBox.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Fly From:.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:16]]></Time>
<TimeTick>1322373496</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="101" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Fly From:.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Fly To:.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:16]]></Time>
<TimeTick>1322373496</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="102" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Fly To:.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[FLIGHT.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:16]]></Time>
<TimeTick>1322373496</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="103" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[FLIGHT.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Name:.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:16]]></Time>
<TimeTick>1322373496</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="104" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Name:.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Insert Order.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:16]]></Time>
<TimeTick>1322373496</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="105" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Insert Order.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Threed Panel Control.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:16]]></Time>
<TimeTick>1322373496</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="106" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Threed Panel Control.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj ><![CDATA[IsContextLoaded]]></Obj>
<Details ><![CDATA[
Object #1Flight Reservation was found.
Object #2Date was found.
Object #3FlyFrom was found.
Object #4FlyTo was found.
Object #5FLIGHT_button was found.
Object #6Name was found.
Object #7Insert Order was found.
Object #8ProgressBar was found.]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:16]]></Time>
<TimeTick>1322373496</TimeTick>
<NodeArgs eType="User" icon="8" nRep="107" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[IsContextLoaded]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[MaskEdBox.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["112811"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:16]]></Time>
<TimeTick>1322373496</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="109" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[MaskEdBox.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[SetDate]]></Obj>
<Details ><![CDATA[Set successfully]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:17]]></Time>
<TimeTick>1322373497</TimeTick>
<NodeArgs eType="User" icon="8" nRep="110" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SetDate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Fly From:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:17]]></Time>
<TimeTick>1322373497</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="112" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Fly From:.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA[SetFlyFrom]]></Obj>
<Details ><![CDATA[Set successfully]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:18]]></Time>
<TimeTick>1322373498</TimeTick>
<NodeArgs eType="User" icon="8" nRep="113" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SetFlyFrom]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Fly To:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[4]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:18]]></Time>
<TimeTick>1322373498</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="115" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Fly To:.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA[SetFlyTo]]></Obj>
<Details ><![CDATA[Set successfully]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:19]]></Time>
<TimeTick>1322373499</TimeTick>
<NodeArgs eType="User" icon="8" nRep="116" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SetFlyTo]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:19]]></Time>
<TimeTick>1322373499</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="118" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Flights Table]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:19]]></Time>
<TimeTick>1322373499</TimeTick>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[From.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:19]]></Time>
<TimeTick>1322373499</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="120" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[From.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:19]]></Time>
<TimeTick>1322373499</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="121" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj ><![CDATA[IsContextLoaded]]></Obj>
<Details ><![CDATA[
Object #1FlyLineWinList was found.
Object #2OK was found.]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:19]]></Time>
<TimeTick>1322373499</TimeTick>
<NodeArgs eType="User" icon="8" nRep="122" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[IsContextLoaded]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[From.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[5]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:19]]></Time>
<TimeTick>1322373499</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="124" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[From.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:19]]></Time>
<TimeTick>1322373499</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="126" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj ><![CDATA[SelectFlyLine]]></Obj>
<Details ><![CDATA[Select successfully]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:19]]></Time>
<TimeTick>1322373499</TimeTick>
<NodeArgs eType="User" icon="8" nRep="127" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SelectFlyLine]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="119" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flights Table]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["Demo"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:19]]></Time>
<TimeTick>1322373499</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="129" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj ><![CDATA[SetName]]></Obj>
<Details ><![CDATA[Set successfully]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:19]]></Time>
<TimeTick>1322373499</TimeTick>
<NodeArgs eType="User" icon="8" nRep="130" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SetName]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Insert Order.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:19]]></Time>
<TimeTick>1322373499</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="132" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Insert Order.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj ><![CDATA[InsertOrder]]></Obj>
<Details ><![CDATA[InsertOrder successfully]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:19]]></Time>
<TimeTick>1322373499</TimeTick>
<NodeArgs eType="User" icon="8" nRep="133" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[InsertOrder]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Flight Reservation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[11/27/2011 - 13:58:19]]></Time>
<TimeTick>1322373499</TimeTick>